// <auto-generated />
using System;
using FiveMinutes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveMinutes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021163528_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveMinutes.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int?>("EducationTestId")
                        .HasColumnType("integer");

                    b.Property<int?>("Question")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EducationTestId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("FiveMinutes.Models.EducationTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EducationTests");
                });

            modelBuilder.Entity("FiveMinutes.Models.FiveMinuteTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FiveMinuteTemplate");
                });

            modelBuilder.Entity("FiveMinutes.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<int?>("FiveMinuteTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FiveMinuteTemplateId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FiveMinutes.Models.Answer", b =>
                {
                    b.HasOne("FiveMinutes.Models.EducationTest", null)
                        .WithMany("Answers")
                        .HasForeignKey("EducationTestId");
                });

            modelBuilder.Entity("FiveMinutes.Models.Question", b =>
                {
                    b.HasOne("FiveMinutes.Models.FiveMinuteTemplate", null)
                        .WithMany("Questions")
                        .HasForeignKey("FiveMinuteTemplateId");
                });

            modelBuilder.Entity("FiveMinutes.Models.EducationTest", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FiveMinutes.Models.FiveMinuteTemplate", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
